//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBankingV1._0
{
    using System;
    
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bankingEntities : DbContext
    {
            
        public bankingEntities()
            : base("name=bankingEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountDetail> accountDetails { get; set; }
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<deposit> deposits { get; set; }
        public virtual DbSet<expens> expenses { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
